server:
  port: 8182

spring:
  jpa:
    defer-datasource-initialization: true
  jackson:
    time-zone: America/Bogota
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:DBProyecto;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
